parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Hippy\Config\Partial\PartialInterface:
      tags: [hippy.config.partial]

  Hippy\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Entity/'
      - '../../Kernel.php'
      - '../tests/'

  Hippy\Config\Config:
    arguments:
      $partials: !tagged_iterator hippy.config.partial
      $root: '%kernel.project_dir%'
      $config: []
