parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Hippy\Config\Partial\AbstractPartial:
      tags: [hippy.config.partial]

  Hippy\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../tests/'

  Hippy\Config\Config:
    arguments:
      $root: '%kernel.project_dir%'
      $partials: !tagged_iterator hippy.config.partial
      $config: []
